### ISSUE TITLE
Default value for Count in Ada.Containers.Vectors.Append.

### ISSUE THREAD

**Issue by Blady-Com** [Ada-Rapporteur-Group/User-Community-Input#76]
Current definitions in Ada.Containers.Vectors:
```
procedure Prepend  (Container : in out Vector; New_Item  : Element_Type; Count : Count_Type := 1);
procedure Append   (Container : in out Vector; New_Item  : Element_Type; Count : Count_Type);
```
Proposal definition:
Add a default value for Count in Append as for Prepend:
`procedure Append (Container : in out Vector; New_Item  : Element_Type; Count  : Count_Type := 1);`

**Comment by sttaft** [comment]
It turns out there is *already* an Append operation where the Count is
implicitly one (paragraph 47.1/5).  We had to handle Append and Prepend
differently because Append needed to match the parameter profile expected
for the "Add_Unnamed" part of the Aggregate aspect.

This is all explained in AI12-0400:

  http://www.ada-auth.org/cgi-bin/cvsweb.cgi/ai12s/ai12-0400-1.txt?rev=1.5

Take care,
-Tucker Taft

**Comment by Blady-Com** [comment]
Thanks for your explanation, it's make sens :-).

Note GNAT FSF 13.2 stil defines in aconvec.ads:
```
   procedure Append
     (Container : in out Vector;
      New_Item  : Vector) renames Append_Vector;
   --  Retained for now for compatibility; AI12-0400 will remove this.
```

**Comment by sttaft** [comment]
This was a very tricky fix, because it created some incompatibilities.  I think this was a first step.  It is probably time now to finish the job and implement what is defined by the Ada 2022 standard.

**Comment by ARG-Editor** [comment]
This question was adequately answered, so I am closing this Issue.
